### ISSUE TITLE
Survival #hunters suggestion

### ISSUE THREAD

**Issue by seedship** [MarioSMB/modpack#43]
I suggest an option where players can do: vcall nbhunters val [0.25] where g_survival_hunter_count <- val

We had a game with 7 players and only 1 hunter, and he kept losing and only 1/7 people got to play hunter

**Comment by MarioSMB** [comment]
A server could add such a vote:  
`alias nhunters "g_survival_hunter_count ${1}"`

The default setting of 0.25 means 25% of the players will be hunters, this number is rounded down so that will produce a hunter every 8 or so players. Given there is only one known Survival server, I may bump that number up a bit.

**Comment by seedship** [comment]
Also when the value is >=1 then it is the number of hunters, and I think having direct control of the number of hunters is also good

**Comment by LegendaryGuard** [comment]
Gotta close the issue as Survival gametype has been moved to the [Xonotic codebase](https://gitlab.com/xonotic/xonotic-data.pk3dir). 
Feel free to open the issue [there](https://gitlab.com/xonotic/xonotic-data.pk3dir/-/issues).
